# updated data 2024 radiolarite

1.NE Alps (AUT) <br>
2.St, Veit Klippen Belt (AUT) <br>
3.N Hungary <br>
4.S Moravia <br>
5.W Slovakia <br>
6.Pieniny MTs,/Podhale Basin (POL) <br>
7.artefakty - Morava <br>

In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

In [61]:
original_df = pd.read_csv('C:/Users/hamro/Desktop/radiolarite_project/2024/pXRF_LA-ICP_MS_spectrophotometry_radiolarites.csv')

In [62]:
df = original_df.copy(deep=True)

In [63]:
df

,Sample ID,Region,"Sample No,",L*,a*,b*,Ti,Mn,Fe,Ni,...,Hf,Ta,W,206Pb,207Pb,208Pb,Bi,Th,U,Notes/remarks
0,ELS01,1,1,47.31,0.73,6.64,233.4,274.7,1444.8,262.7,...,<LOQ,<LOQ,"117,23","6,05","5,91","5,7",<LOD,"0,83","0,45",NaN
1,ELS02,1,2,63.84,-1.34,6.07,248.1,674.4,1017.2,258.2,...,<LOQ,<LOQ,"82,38","13,56","13,11","13,35",<LOQ,"1,38","0,53",NaN
2,ELS04,1,3,53.79,2.85,10.85,309.1,519.2,1736.4,288.0,...,<LOQ,<LOQ,"137,12","4,2","3,81","3,91",<LOD,"0,89","0,47",NaN
3,ELS05,1,4,66.05,-4.15,7.98,758.1,268.2,3902.1,275.2,...,<LOQ,<LOQ,"112,29","3,28","2,89","3,05",<LOQ,"1,33","0,31",NaN
4,ELS07,1,5,49.54,15.01,13.63,264.1,326.4,1895.6,262.3,...,<LOQ,<LOQ,"5014,15","51,21","47,47","48,74",<LOQ,<LOQ,"3,78",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,HAR5,7,257,42.30,9.52,12.38,165.0,172.6,757.5,253.2,...,<LOD,<LOQ,"20,56","10,01","9,57","8,76",<LOD,"0,33","0,76",NaN
257,HAR6,7,258,41.28,11.92,16.80,155.0,162.1,734.3,241.6,...,<LOQ,"0,52","15,13","16,86","14,75","19,61",<LOQ,"0,92","1,15",NaN
258,HAR7,7,259,43.69,9.15,16.08,165.4,173.0,818.4,253.4,...,<LOQ,"0,52","23,95","13,91","12,8","12,88",<LOQ,"0,73","1,45",NaN
259,HAR8,7,260,34.68,2.40,4.16,171.8,179.6,645.9,240.6,...,<LOQ,"0,25","11,85","7,65","7,76","7,29",<LOD,"0,45","0,94",NaN
260,ITA1,8,261,42.20,10.68,13.45,168.9,176.6,707.3,257.6,...,<LOD,"0,24","3,36","42,99","42,05","39,33",<LOQ,"0,52","0,64",NaN

In [64]:
rows_to_drop = df[df['Region'] == 8].index

In [65]:
df.drop(rows_to_drop, inplace=True)

### Data cleaning
- removing the 8th region since only one record is available 
- the remaining groups including the following regions:
1. NE Alps (AUT)
2. St, Veit Klippen Belt (AUT)
3. N Hungary
4. S Moravia
5. W Slovakia
6. Pieniny MTs,/Podhale Basin (POL)
7. artefakty - Morava

### create seperate file for each method
- creating deep copy

In [47]:
spectrophotometry = df.copy(deep=True)

In [48]:
xrf = df.copy(deep=True)

In [49]:
ablation = df.copy(deep=True)

In [51]:
ablation_xrf_spectrophotometry = df.copy(deep=True)

## xrf
- first xrf - getting rid of the rest of the table
- elements included - Ti,Mn,Fe,Ni,Cu,Zn,As,Rb,Sr

In [12]:
xrf = xrf[['Sample ID','Region','Ti','Mn','Fe','Ni','Cu','Zn','As','Rb','Sr']]

In [13]:
xrf_wihtout_id = xrf[['Region','Ti','Mn','Fe','Ni','Cu','Zn','As','Rb','Sr']]

In [14]:
# no zero values
xrf.isnull().sum()

Sample ID    0
Region       0
Ti           0
Mn           0
Fe           0
Ni           0
Cu           0
Zn           0
As           0
Rb           0
Sr           0
dtype: int64

In [15]:
regions = xrf_wihtout_id.groupby(by="Region").mean()

In [16]:
regions

,Ti,Mn,Fe,Ni,Cu,Zn,As,Rb,Sr
Region,,,,,,,,,
1,252.333500,324.261750,1129.093250,281.518500,307.472500,339.481750,3.597250,15.374000,134.239000
2,333.451852,430.451852,1892.435185,358.242593,348.394444,324.851852,4.537037,23.016667,103.583333
3,197.257143,201.735714,833.292857,255.957143,283.814286,269.542857,3.400000,11.528571,34.892857
4,414.765517,314.879310,2030.041379,287.100000,310.437931,327.844828,4.334483,20.917241,105.534483
5,267.126316,242.252632,1548.410526,280.331579,318.061404,298.100000,3.896491,18.857895,81.280702
6,232.675000,266.959375,817.603125,289.662500,313.078125,290.784375,3.684375,13.612500,129.131250
7,167.429412,175.088235,609.979412,249.000000,298.223529,272.897059,3.476471,10.250000,24.929412

In [17]:
xrf_wihtout_id['Region'].value_counts()

Region
5    57
2    54
1    40
7    34
6    32
4    29
3    14
Name: count, dtype: int64

### Convertion absolute XRF data into relative measurements 
- data into ratios for compositional analysis involves converting absolute measurements into relative ones, so each sample's component measurements sum to a constant value (often 100%, representing the whole composition).

In [18]:
xrf.columns

Index(['Sample ID', 'Region', 'Ti', 'Mn', 'Fe', 'Ni', 'Cu', 'Zn', 'As', 'Rb',
       'Sr'],
      dtype='object')

In [19]:
xrf_info = xrf[['Sample ID', 'Region']]
xrf_quantitative = xrf.drop(['Sample ID', 'Region'], axis=1)

In [20]:
xrf_quantitative_transform = xrf_quantitative.sum(axis=1)
xrf_ratio = (xrf_quantitative.div(xrf_quantitative_transform, axis=0))

In [21]:
# Divide each component by the sum and multiply by 100 to get percentages
xrf_ratio = (xrf_quantitative.div(xrf_quantitative_transform, axis=0))

In [22]:
# concatenate columns side by side
xrf_trans = pd.concat([xrf_info, xrf_ratio], axis=1)

##### deep copy xrf

In [23]:
xrf_trans_copy = xrf_trans.copy(deep=True)

In [24]:
xrf_trans_copy

,Sample ID,Region,Ti,Mn,Fe,Ni,Cu,Zn,As,Rb,Sr
0,ELS01,1,0.078217,0.092058,0.484182,0.088036,0.106803,0.115382,0.000938,0.005630,0.028753
1,ELS02,1,0.084537,0.229794,0.346599,0.087979,0.096395,0.119020,0.002181,0.005656,0.027838
2,ELS04,1,0.084706,0.142282,0.475843,0.078924,0.088762,0.104985,0.001288,0.004576,0.018635
3,ELS05,1,0.125688,0.044466,0.646943,0.045626,0.052938,0.062819,0.000597,0.009284,0.011639
4,ELS07,1,0.075652,0.093498,0.542996,0.075136,0.087998,0.096190,0.001232,0.004870,0.022429
...,...,...,...,...,...,...,...,...,...,...,...
255,HAR4,7,0.075535,0.078997,0.473379,0.105013,0.131980,0.117263,0.003333,0.004415,0.010086
256,HAR5,7,0.083646,0.087499,0.384011,0.128359,0.154111,0.144023,0.001572,0.005019,0.011761
257,HAR6,7,0.082071,0.085831,0.388807,0.127925,0.153394,0.141745,0.001536,0.004924,0.013767
258,HAR7,7,0.080541,0.084242,0.398520,0.123393,0.157966,0.135421,0.002240,0.005064,0.012612
259,HAR8,7,0.093532,0.097779,0.351644,0.130989,0.154236,0.148519,0.001797,0.005934,0.015571

In [25]:
ID_drop = xrf_trans_copy.drop('Sample ID', axis=1, inplace=True)

In [26]:
xrf_trans_copy

,Region,Ti,Mn,Fe,Ni,Cu,Zn,As,Rb,Sr
0,1,0.078217,0.092058,0.484182,0.088036,0.106803,0.115382,0.000938,0.005630,0.028753
1,1,0.084537,0.229794,0.346599,0.087979,0.096395,0.119020,0.002181,0.005656,0.027838
2,1,0.084706,0.142282,0.475843,0.078924,0.088762,0.104985,0.001288,0.004576,0.018635
3,1,0.125688,0.044466,0.646943,0.045626,0.052938,0.062819,0.000597,0.009284,0.011639
4,1,0.075652,0.093498,0.542996,0.075136,0.087998,0.096190,0.001232,0.004870,0.022429
...,...,...,...,...,...,...,...,...,...,...
255,7,0.075535,0.078997,0.473379,0.105013,0.131980,0.117263,0.003333,0.004415,0.010086
256,7,0.083646,0.087499,0.384011,0.128359,0.154111,0.144023,0.001572,0.005019,0.011761
257,7,0.082071,0.085831,0.388807,0.127925,0.153394,0.141745,0.001536,0.004924,0.013767
258,7,0.080541,0.084242,0.398520,0.123393,0.157966,0.135421,0.002240,0.005064,0.012612
259,7,0.093532,0.097779,0.351644,0.130989,0.154236,0.148519,0.001797,0.005934,0.015571

# Model Training

In [29]:
xrf_trans_copy['Region'].value_counts()

Region
5    57
2    54
1    40
7    34
6    32
4    29
3    14
Name: count, dtype: int64

### Average accuracy

In [32]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np

# Your data preparation code...
X = xrf_trans_copy.drop(['Region'], axis=1)  # features
y = xrf_trans_copy['Region']  # target labels

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# LDA classifier with 'svd' solver
lda = LinearDiscriminantAnalysis(solver='svd')

# No parameter grid needed for 'svd' solver
# Fit the model directly
lda.fit(X_train, y_train)

# Predictions on the test set
lda_pred = lda.predict(X_test)

# Evaluate the model
lda_accuracy = np.mean(lda_pred == y_test)
print("LDA Accuracy:", lda_accuracy)

LDA Accuracy: 0.5576923076923077

In [33]:
import numpy as np

# Example manual input for seven features
input_values = [0.5, 0.2, 0.7, 0.1, 0.8, 0.6, 0.3,0.2, 0.1]  # replace these with your actual values

# Ensure the input is in the correct shape (1 row with 7 columns)
input_array = np.array([input_values])

# Predict the region using the LDA model
predicted_region = lda.predict(input_array)

# Since `predict` returns an array, we take the first element
region = predicted_region[0]

print(f"The model predicts region: {region}")

The model predicts region: 5

C:\Users\hamro\Anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearDiscriminantAnalysis was fitted with feature names
  warnings.warn(

### result in format: region + probability

In [39]:
import numpy as np

# Example manual input for seven features manually put it
input_values = [0.004706, 0.242282, 0.475843, 0.078924, 0.008762, 0.104985, 0.004288, 0.004576, 0.018635] 

# 9 features input
input_array = np.array([input_values])

# Check if the LDA model has the predict_proba method
if hasattr(lda, "predict_proba"):
    # predict for all classes
    probabilities = lda.predict_proba(input_array)

    # highest probability
    class_index = np.argmax(probabilities, axis=1)[0]
    
    # class + 1 since it is indexed from 0
    predicted_class_label = class_index + 1
    
    # Obtain the highest probability
    highest_probability = probabilities[0, class_index]
    
    print(f"The model predicts region: {predicted_class_label} with a probability of {highest_probability:.2f}")
else:
    print("This model does not support probability estimates.")

The model predicts region: 1 with a probability of 0.53

C:\Users\hamro\Anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearDiscriminantAnalysis was fitted with feature names
  warnings.warn(

In [ ]:
from joblib import dump



# Export the model to a file
dump(lda, 'lda_model_xrf.joblib')